version: "3"

services:
  api-gateway:
    build: .
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.75"
          memory: "1536M"
    environment:
      DATABASE_URL: postgres://postgres:pass123@postgres:5432/diesel_demo
    ports:
      - "3000"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"
    networks:
      - mynetwork

networks:
  mynetwork:
