version: "3"

services:
  api-gateway:
    build: .
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.75"
          memory: "1536M"
    environment:
      DATABASE_URL: postgresql://postgres:pass123@postgres:5432/warriors
    ports:
      - "3000"
    networks:
      - mynetwork
    depends_on:
      - redis

  nginx:
    image: nginx:1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"
    networks:
      - mynetwork
    depends_on:
      - api-gateway

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
