version: "3"

services:
  api-gateway-1:
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:pass123@db_part1:5432/warriors"
      SHARD: 1
    ports:
      - "3000"
    networks:
      - mynetwork

  api-gateway-2:
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:pass123@db_part2:5432/warriors"
      SHARD: 2
    ports:
      - "3001"
    networks:
      - mynetwork

  nginx:
    image: nginx:1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"
    networks:
      - mynetwork
    depends_on:
      - api-gateway-1
      - api-gateway-2

networks:
  mynetwork:
