application:
  port: 3000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "newsletter"
email_client:
  base_url: "http://localhost"
  authorisation_token: "my-secret-token"
  timeout_milliseconds: 10000
# 6379 is Redis' default port
redis_uri: "redis://127.0.0.1:6379"
