// Generated by diesel_ext

use diesel::{Insertable, Queryable, Selectable};
use crate::schema::warriors;

#[derive(Debug, serde::Serialize, Selectable, Queryable)]
pub struct Warrior {
    pub id: i32,
    pub name: String,
    pub dob: String,
}

#[derive(Debug, serde::Deserialize, Insertable)]
#[diesel(table_name = crate::schema::warriors)]
pub struct NewWarrior {
    pub name: String,
    pub dob: Option<String>,
}