CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS warriors_2 (
  id VARCHAR PRIMARY KEY, 
  name VARCHAR NOT NULL,
  dob VARCHAR NOT NULL,
  fight_skills VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS skills_2 (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL
);

CREATE INDEX idx_warriors_id ON warriors_2 (id);